/*
 * firmware_adresses.h
 *
 *  Created on: Mar 13, 2025
 *      Author: lehmann
 */

#ifndef FIRMWARE_ADRESSES_H_
#define FIRMWARE_ADRESSES_H_



#define TWIPR_REGISTER_MAP_GENERAL 0x01

// Register Maps and Messages on the CM4
#define CM4_STANDARD_REGISTER_MAP 0x01

// Register Addresses
#define REG_ADDRESS_R_FIRMWARE_STATE 0x01
#define REG_ADDRESS_R_FIRMWARE_TICK 0x02
#define REG_ADDRESS_R_FIRMWARE_REVISION 0x03
#define REG_ADDRESS_F_FIRMWARE_DEBUGFUNCTION 0x04
#define REG_ADDRESS_F_FIRMWARE_BEEP 0x05
#define REG_ADDRESS_R_BOARD_REVISION 0x06

#define REG_ADDRESS_F_EXTERNAL_LED 0x07
#define REG_ADDRESS_RW_DEBUG_1 0x08


#define REG_ADDRESS_R_CONTROL_MODE 0x10
#define REG_ADDRESS_F_CONTROL_SET_MODE 0x11
#define REG_ADDRESS_F_CONTROL_SET_K 0x12
#define REG_ADDRESS_F_CONTROL_SET_FORWARD_PID 0x13
#define REG_ADDRESS_F_CONTROL_SET_TURN_PID 0x14
#define REG_ADDRESS_F_CONTROL_SET_DIRECT_INPUT 0x15
#define REG_ADDRESS_F_CONTROL_SET_BALANCING_INPUT 0x16
#define REG_ADDRESS_F_CONTROL_SET_SPEED_INPUT 0x17
#define REG_ADDRESS_F_CONTROL_GET_CONFIGURATION 0x18
#define REG_ADDRESS_F_CONTROL_SET_CONFIGURATION 0x19

#define REG_ADDRESS_RW_MAX_WHEEL_SPEED 0x20

#define REG_ADDRESS_F_SEQUENCE_LOAD 0x21
#define REG_ADDRESS_F_SEQUENCE_START 0x22
#define REG_ADDRESS_F_SEQUENCE_STOP 0x23
#define REG_ADDRESS_F_SEQUENCE_READ 0x24

#define REG_ADRESS_F_ENABLE_VELOCITY_INTEGRAL_CONTROL 0x31
#define REG_ADDRESS_F_SET_VELOCITY_INTEGRAL_CONTROL_CONFIG 0x32

#define REG_ADDRESS_F_ACTUATORS_SET_TORQUE_SINGLE 0x43
#define REG_ADDRESS_F_ACTUATORS_SEND_PING_SINGLE 0x44
#define REG_ADDRESS_F_ACTUATORS_SET_LED_SINGLE 0x45
#define REG_ADDRESS_F_ACTUATORS_SET_POSITION_SINGLE 0x46

#define REG_ADDRESS_R_ACTUATORS_GET_VOLTAGE_SINGLE 0x4A
#define REG_ADDRESS_R_ACTUATORS_GET_TEMPERATURE_SINGLE 0x4B
#define REG_ADDRESS_R_ACTUATORS_GET_GOAL_POSITION_SINGLE 0x4C
#define REG_ADDRESS_R_ACTUATORS_GET_PRESENT_POSITION_SINGLE 0x4D

#define REG_ADDRESS_F_ACTUATORS_SET_TORQUE_ALL 0x52
#define REG_ADDRESS_F_ACTUATORS_SET_LED_ALL 0x53
#define REG_ADDRESS_F_ACTUATORS_SET_POSITION_ALL 0x54

#define REG_ADDRESS_R_ACTUATORS_GET_VOLTAGE_ALL 0x57
#define REG_ADDRESS_R_ACTUATORS_GET_TEMPERATURE_ALL 0x58
#define REG_ADDRESS_R_ACTUATORS_GET_GOAL_POSITION_ALL 0x59
#define REG_ADDRESS_R_ACTUATORS_GET_PRESENT_POSITION_ALL 0x5A


#define REG_ADDRESS_F_ESTIMATION_SET_THETA_OFFSET 0x50

#define REG_ADDRESS_F_FIRMWARE_RESET 0xF1


// Messages
#define BILBO_MESSAGE_PRINT 0xDD
#define BILBO_MESSAGE_ERROR 0x10
#define BILBO_MESSAGE_SEQUENCER_EVENT 0x41




#endif /* FIRMWARE_ADRESSES_H_ */
