stm32:
  reset: false

testbed:
#  id: track
  id: lab-hannover

tracker:
  enabled: true
#  server: palantir.lan
  server: 192.168.8.163

joystick:
  enabled: true

sound:
  volume: 0.25
  voice: robot  # female, male, or robot

control:
  auto_position_mode: true  # auto-switch to POSITION when calling move_to/turn_to wrappers

paths:
  main: '~/robot'

misc:
  warn_on_sample_batching: true

