paths:
  experiments: ./definitions/tests/
  reference_trajectories: ./definitions/references/

testbed: track

robots:
  autostart: false
  autostop: false

extensions:
  display: true
  limbobar: false
  timecode: true
  joystick: true

simulation:
  enabled: true
  Ts: 0.01
  robots: null

tracker:
  enabled: true
  server: palantir.lan
  sample_rate: 50
  outlier_filter:
    enabled: true
    window_size: 3
  tracked_robots:
    - bilbo2

mdns:
  enabled: true
  hostname: bilbolab  # Will be accessible as bilbolab.local
  # To access without port (bilbolab.local/gui instead of bilbolab.local:8400/gui),
  # set use_port_80 to true. This requires running the application with sudo.
  use_port_80: true
