# =====================================================================================
#  Generates printable ArUco marker images for the servo trigger IDs (SERVO_TRIGGER_IDS
#  in art_project_frodo.py), using the EXACT SAME dictionary as the detector
#  (ARUCO_DICT_TYPE in aruco_utils.py).
#
#  WHY THIS EXISTS: the metronome-tip markers were made with an online ArUco
#  generator, not OpenCV itself - online generators don't always use the same
#  dictionary/bit layout as cv2.aruco.DICT_4X4_1000, so a marker printed as
#  "ID 997" there can decode to a different ID (or nothing at all) here. Markers
#  generated by this script are guaranteed to match what the robot's detector
#  (create_aruco_detector() in aruco_utils.py) expects.
#
#  Usage: python generate_servo_markers.py
#  Output: aruco_marker_<id>.png next to this file, one per SERVO_TRIGGER_IDS entry.
# =====================================================================================
import cv2.aruco as aruco
import cv2
import os

from aruco_utils import ARUCO_DICT_TYPE

MARKER_IDS = (995, 996, 997, 998, 999)
MARKER_SIDE_PX = 600   # print large - the whole point is reliable detection at a distance
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

if __name__ == "__main__":
    dictionary = aruco.getPredefinedDictionary(ARUCO_DICT_TYPE)
    for marker_id in MARKER_IDS:
        img = aruco.generateImageMarker(dictionary, marker_id, MARKER_SIDE_PX)
        out_path = os.path.join(OUTPUT_DIR, f"aruco_marker_{marker_id}.png")
        cv2.imwrite(out_path, img)
        print(f"wrote {out_path}")
