/*
 * firmware_adresses.h
 *
 *  Created on: Mar 13, 2025
 *      Author: lehmann
 */

#ifndef FIRMWARE_ADRESSES_H_
#define FIRMWARE_ADRESSES_H_

#define BILBO_REGISTER_MAP_GENERAL 0x01

// Register Maps and Messages on the CM4
#define CM4_STANDARD_REGISTER_MAP 0x01

// Register Addresses
// ================================
// 0x01 - 0x0F : SYSTEM / FIRMWARE
// ================================
#define REG_ADDRESS_R_FIRMWARE_STATE            0x01
#define REG_ADDRESS_R_FIRMWARE_TICK             0x02
#define REG_ADDRESS_R_FIRMWARE_REVISION         0x03
#define REG_ADDRESS_R_FIRMWARE_INFO              0x04

#define REG_ADDRESS_F_FIRMWARE_DEBUGFUNCTION    0x05
#define REG_ADDRESS_F_FIRMWARE_BEEP             0x06

#define REG_ADDRESS_F_EXTERNAL_LED              0x07
#define REG_ADDRESS_F_ALL_EXTERNAL_LEDS         0x08
#define REG_ADDRESS_RW_DEBUG_1                  0x09
// 0x0A - 0x0F reserved

// ================================
// 0x20 - 0x2F : CONTROL (CORE)
// ================================
#define REG_ADDRESS_R_CONTROL_MODE              0x20
#define REG_ADDRESS_F_CONTROL_SET_MODE          0x21
#define REG_ADDRESS_F_CONTROL_SET_K             0x22
#define REG_ADDRESS_F_CONTROL_SET_FORWARD_PID   0x23
#define REG_ADDRESS_F_CONTROL_SET_TURN_PID      0x24
#define REG_ADDRESS_F_CONTROL_SET_DIRECT_INPUT  0x25
#define REG_ADDRESS_F_CONTROL_SET_BALANCING_INPUT 0x26
#define REG_ADDRESS_F_CONTROL_SET_SPEED_INPUT   0x27
#define REG_ADDRESS_F_CONTROL_GET_CONFIGURATION 0x28
#define REG_ADDRESS_F_CONTROL_SET_CONFIGURATION 0x29

#define REG_ADDRESS_RW_MAX_WHEEL_SPEED          0x2A
#define REG_ADDRESS_F_CONTROL_NUDGE             0x2B
// 0x2C - 0x2F reserved

// ================================
// 0x30 - 0x3F : CONTROL (CONFIG + ENABLES)
// ================================
#define REG_ADDRESS_F_CONTROL_SET_VELOCITY_CONFIG_V        0x30
#define REG_ADDRESS_F_CONTROL_SET_VELOCITY_CONFIG_V_FF     0x31
#define REG_ADDRESS_F_CONTROL_SET_VELOCITY_CONFIG_PSIDOT   0x32
#define REG_ADDRESS_F_CONTROL_SET_VELOCITY_CONFIG_PSIDOT_FF 0x33

#define REG_ADDRESS_F_CONTROL_SET_POSITION_CONFIG          0x34
#define REG_ADDRESS_F_CONTROL_SET_TIC_CONFIG               0x35
#define REG_ADDRESS_F_CONTROL_SET_VIC_CONFIG               0x36
#define REG_ADDRESS_F_CONTROL_SET_MAX_TORQUE               0x37

#define REG_ADDRESS_F_ENABLE_VELOCITY_INTEGRAL_CONTROL     0x38
#define REG_ADDRESS_F_SET_VELOCITY_INTEGRAL_CONTROL_CONFIG 0x39
#define REG_ADDRESS_F_ENABLE_TIC                           0x3A
#define REG_ADDRESS_F_ENABLE_VIC                           0x3B
#define REG_ADDRESS_F_CONTROL_SET_PSI_CONFIG               0x3C
#define REG_ADDRESS_F_ENABLE_PSI                           0x3D
#define REG_ADDRESS_F_SET_PSI_SETPOINT                     0x3E
// 0x3F reserved

// ================================
// 0x40 - 0x4F : SEQUENCER
// ================================
#define REG_ADDRESS_F_SEQUENCE_LOAD           0x40
#define REG_ADDRESS_F_SEQUENCE_START          0x41
#define REG_ADDRESS_F_SEQUENCE_STOP           0x42
#define REG_ADDRESS_F_SEQUENCE_READ           0x43
// 0x44 - 0x4F reserved

// ================================
// 0x60 - 0x6F : POSITION CONTROL
// ================================
#define REG_ADDRESS_F_POSITION_SET_CONFIG         0x60
#define REG_ADDRESS_F_POSITION_GET_CONFIG         0x61
#define REG_ADDRESS_F_POSITION_CLEAR_PATH         0x62
#define REG_ADDRESS_F_POSITION_ADD_PATH_POINT     0x63
#define REG_ADDRESS_F_POSITION_START_PATH         0x64
#define REG_ADDRESS_F_POSITION_PAUSE_PATH         0x65
#define REG_ADDRESS_F_POSITION_RESUME_PATH        0x66
#define REG_ADDRESS_F_POSITION_ABORT_PATH         0x67
#define REG_ADDRESS_R_POSITION_PATH_STATE         0x68
#define REG_ADDRESS_R_POSITION_DATA               0x69
#define REG_ADDRESS_R_POSITION_PATH_POINT_COUNT   0x6A
#define REG_ADDRESS_F_POSITION_TURN_TO_HEADING    0x6B
#define REG_ADDRESS_F_POSITION_MOVE_TO_POINT      0x6C
#define REG_ADDRESS_F_POSITION_RESET              0x6D
#define REG_ADDRESS_F_POSITION_ADD_STOP_INDEX     0x6E
#define REG_ADDRESS_F_POSITION_ADD_PATH_BATCH    0x6F

// ================================
// 0x50 - 0x5F : ESTIMATION
// ================================
#define REG_ADDRESS_F_ESTIMATION_SET_THETA_OFFSET    0x50
#define REG_ADDRESS_F_ESTIMATION_SET_POSITION_STATE  0x51
#define REG_ADDRESS_F_ESTIMATION_SET_POSITION_UPDATE 0x52
#define REG_ADDRESS_F_ESTIMATION_RESET               0x53
#define REG_ADDRESS_F_ESTIMATION_GET_VELOCITY_LPF    0x54
#define REG_ADDRESS_F_ESTIMATION_SET_VELOCITY_LPF    0x55
#define REG_ADDRESS_F_ESTIMATION_GET_PSIDOT_LPF      0x56
#define REG_ADDRESS_F_ESTIMATION_SET_PSIDOT_LPF      0x57
#define REG_ADDRESS_F_ESTIMATION_SET_DEAD_RECKONING_ENABLE 0x58
#define REG_ADDRESS_F_ESTIMATION_GET_THETA_DOT_LPF       0x59
#define REG_ADDRESS_F_ESTIMATION_SET_THETA_DOT_LPF       0x5A
#define REG_ADDRESS_F_ESTIMATION_GET_CONFIG              0x5B
#define REG_ADDRESS_F_ESTIMATION_SET_CONFIG              0x5C

// ================================
// 0xF0 - 0xFF : SYSTEM SPECIAL
// ================================
#define REG_ADDRESS_F_FIRMWARE_RESET          0xF0
#define REG_ADDRESS_F_DRIVE_RESET            0xF1
// 0xF2 - 0xFF reserved

// Messages
#define BILBO_MESSAGE_PRINT 0xDD
#define BILBO_MESSAGE_ERROR 0x10
#define BILBO_MESSAGE_SEQUENCER_EVENT 0x41
#define BILBO_MESSAGE_CONTROL_EVENT 0x51
#define BILBO_MESSAGE_WAYPOINT_EVENT 0x52
#define BILBO_MESSAGE_POSITION_CONTROL_EVENT 0x53
#define BILBO_MESSAGE_DRIVE_EVENT 0x54

#endif /* FIRMWARE_ADRESSES_H_ */
