import enum


class BILBO_AddressTables(enum.IntEnum):
    REGISTER_TABLE_GENERAL = 0x01

import enum


class BILBO_SystemAddresses(enum.IntEnum):
    # 0x01 - 0x0F : SYSTEM / FIRMWARE
    FIRMWARE_STATE = 0x01
    FIRMWARE_TICK = 0x02
    FIRMWARE_REVISION = 0x03
    FIRMWARE_INFO = 0x04

    FIRMWARE_DEBUGFUNCTION = 0x05
    FIRMWARE_BEEP = 0x06

    EXTERNAL_LED = 0x07
    ALL_EXTERNAL_LEDS = 0x08
    DEBUG_1_RW = 0x09

    # 0xF0 - 0xFF : SYSTEM SPECIAL
    FIRMWARE_RESET = 0xF0
    DRIVE_RESET = 0xF1


class BILBO_ControlAddresses(enum.IntEnum):
    # 0x20 - 0x2F : CONTROL (CORE)
    READ_MODE = 0x20
    SET_MODE = 0x21
    SET_K = 0x22
    SET_FORWARD_PID = 0x23
    SET_TURN_PID = 0x24
    SET_DIRECT_INPUT = 0x25
    SET_BALANCING_INPUT = 0x26
    SET_SPEED_INPUT = 0x27
    GET_CONFIGURATION = 0x28
    SET_CONFIGURATION = 0x29

    RW_MAX_WHEEL_SPEED = 0x2A
    NUDGE = 0x2B
    # 0x2C - 0x2F reserved

    # 0x30 - 0x3F : CONTROL (CONFIG + ENABLES)
    SET_VELOCITY_CONFIG_V = 0x30
    SET_VELOCITY_CONFIG_V_FF = 0x31
    SET_VELOCITY_CONFIG_PSIDOT = 0x32
    SET_VELOCITY_CONFIG_PSIDOT_FF = 0x33

    SET_POSITION_CONFIG = 0x34
    SET_TIC_CONFIG = 0x35
    SET_VIC_CONFIG = 0x36
    SET_MAX_TORQUE = 0x37

    ENABLE_VELOCITY_INTEGRAL_CONTROL = 0x38
    SET_VELOCITY_INTEGRAL_CONTROL_CONFIG = 0x39
    ENABLE_TIC = 0x3A
    ENABLE_VIC = 0x3B
    SET_PSI_CONFIG = 0x3C
    ENABLE_PSI = 0x3D
    SET_PSI_SETPOINT = 0x3E


class BILBO_PositionControlAddresses(enum.IntEnum):
    # 0x60 - 0x6F : POSITION CONTROL
    SET_CONFIG = 0x60
    GET_CONFIG = 0x61
    CLEAR_PATH = 0x62
    ADD_PATH_POINT = 0x63
    START_PATH = 0x64
    PAUSE_PATH = 0x65
    RESUME_PATH = 0x66
    ABORT_PATH = 0x67
    READ_PATH_STATE = 0x68
    READ_DATA = 0x69
    READ_PATH_POINT_COUNT = 0x6A
    TURN_TO_HEADING = 0x6B
    MOVE_TO_POINT = 0x6C
    RESET = 0x6D
    ADD_STOP_INDEX = 0x6E
    ADD_PATH_BATCH = 0x6F


class BILBO_SequencerAddresses(enum.IntEnum):
    # 0x40 - 0x4F : SEQUENCER
    LOAD = 0x40
    START = 0x41
    STOP = 0x42
    READ = 0x43


class BILBO_EstimationAddresses(enum.IntEnum):
    # 0x50 - 0x5F : ESTIMATION
    SET_THETA_OFFSET = 0x50
    SET_POSITION_STATE = 0x51
    SET_POSITION_UPDATE = 0x52
    RESET = 0x53
    GET_VELOCITY_LPF = 0x54
    SET_VELOCITY_LPF = 0x55
    GET_PSIDOT_LPF = 0x56
    SET_PSIDOT_LPF = 0x57
    SET_DEAD_RECKONING_ENABLE = 0x58
    GET_THETA_DOT_LPF = 0x59
    SET_THETA_DOT_LPF = 0x5A
    GET_CONFIG = 0x5B
    SET_CONFIG = 0x5C
